### ISSUE TITLE
Broken nats-cli arm64 binary

### ISSUE THREAD

**Issue by jamm3e3333** [nats-io/natscli#1029]
### Observed behavior

When I installed the latest version (v0.1.4) of nats cli in arm64 linux image and trying to use nats-cli  it says "Segmentation fault" so I assume that smth is wrong with the binary. I tried to install it like this:

```sh
# curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | sh && mv nats /usr/local/bin/

  ==> Downloading github.com/nats-io/natscli/nats@latest
  ==> Resolved version latest to 0345fb1
  ==> Downloading binary for linux arm64
  ==>   URL: https://binaries.nats.dev/binary/github.com/nats-io/natscli/nats?os=linux&arch=arm64&version=0345fb1
  ==> Installing nats to .
  ==> Installation complete
  #nats --version
Segmentation fault
  ```

when I install nats-cli v0.1.3 everything works fine

### Expected behavior

I want it to work, that's all xD

### Server and client version

nats-server version: `2.9.15` (not sure about that)
nats-cli version: `v0.1.4`

**Comment by ripienaar** [comment]
Hmm, I dont have any arm64 machines, can you try the official released binary from the releases page? Same story?

**Comment by mprimi** [comment]
I bumped into this one yesterday. It's not an issue with this project but rather of `nats-binaries`, the downloaded binary is half the expected size, meaning probably the backend store for the latest version is corrupted.

@wallyqs can you nuke the cache?
@jamm3e3333 if you download the previous commit (by SHA) rather than `main`, it will probably work (it did for me)

**Comment by wallyqs** [comment]
Thanks for the report, I think this should be resolved now.

**Comment by akshatggupta** [comment]
Hi, I ran into a similar segmentation fault issue when running `nats --version`, but after debugging it further, it seems the problem may be due to a corrupted binary rather than a runtime compatibility issue.

Environment:

WSL (Ubuntu)
Architecture: `x86_64`
Installed via: `curl ... | sh`

Symptoms:

nats --version → `segmentation fault`

`file $(which nats)` shows:

ELF 64-bit LSB executable, x86-64, statically linked, too large section header offset ...
ldd crashes with exit code 135

From what I understand, the too large section header offset indicates the binary itself is malformed/corrupted.
I also tried the suggestion of downloading a previous commit (by SHA) instead of `main`, and in some cases it does seem to work, which initially made it look like a version-specific issue.

However, after further debugging, it appears the root cause (at least in my case) is a corrupted binary rather than a specific commit.

May be Re-downloading the binary manually (without piping) or rebuilding from source resolves the issue???

<img width="1350" height="429" alt="Image" src="https://github.com/user-attachments/assets/480fed35-59e1-4ad0-98d7-66a992689109" />

**Comment by ripienaar** [comment]
The supported installation here is from our release page, do those binaries work?

**Comment by akshatggupta** [comment]
thanks for the suggestion @ripienaar  i tried installing directly from the official release page instead of using the install script.

The binary from the release page works correctly (`nats --version` runs without any issues).

It seems the problem I was facing was due to a corrupted binary from the install script (possibly related to piping or the environment).

Thanks for pointing me in the right direction :))
