### ISSUE TITLE
Issue:  dupe-window isn't honored on the command line

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/natscli#17]
```
$ natscli stream create --user=jsadmin --password=password --subjects=foo --storage=file --retention=limits --ack --max-msgs=100 --max-bytes=204800 --max-age="1h" --discard=old --max-msg-size=20480 --dupe-window="" test-stream

? Duplicate tracking time window 
Stream test-stream was created

Information for Stream test-stream
```

**Comment by ripienaar** [comment]
Was aiming for being explicit about what happens because it's required to be given. 

And the problem with this CLI override pattern is that if I made it default to say 2 minutes - or really anything - I wont know the difference between the default and supplied and have to ask anyway.

I guess the question is what did you hope to achieve by setting it `""`? You cant turn dupe tracking off

**Comment by ripienaar** [comment]
ping @ColinSullivan1
