### ISSUE TITLE
nats server check server reports incorrect gateways data

### ISSUE THREAD

**Issue by ripienaar** [nats-io/natscli#327]
https://github.com/nats-io/natscli/blob/26b73c71331635eb16018222da70f4e59231041b/cli/server_check_command.go#L490

It uses Remotes there, not Gateways

**Comment by ripienaar** [comment]
Actually, Remotes appear right, need to investigate more why i see 2 when it should be 0 in a test env

**Comment by ripienaar** [comment]
@derekcollison @kozlovic I was under the, apparently wrong, impression that vz Remotes are active gateway connections and vz Routes active route connections. 

 But in some tests I see Remotes=2 while no gateways are defined.  What does Remotes mean in vz? In code I see it used in both gateway and routes code. And if Remotes isn't active gateway connections - then I don't think there is a vz var for that.

**Comment by kozlovic** [comment]
`Varz.Remotes` stores the number of routes, not gateways. This is the only place where we capture it for monitoring https://github.com/nats-io/nats-server/blob/297b44394f92e990da450178cffaa7adecc88837/server/monitor.go#L1481, and here the only place where we set it: https://github.com/nats-io/nats-server/blob/297b44394f92e990da450178cffaa7adecc88837/server/route.go#L1422. So this number is the number of active routes.

**Comment by ripienaar** [comment]
Ah, I missread `gw.Remotes` and `s.Remotes` earlier today, ok, so I don't think we have anything indicating active gateway connections looks like.  And vz.Routes is then the total known routes rather than active?

Essentially I want to assert that currently there are 3 connected routes - 1 might be retrying so the client exist but its not connected. Ditto gateways. Suspect we just don't have this information today and I've been confused about these 2 numbers for a long time hehe

**Comment by kozlovic** [comment]
Well, to me it looks like `s.routes` and `s.remotes` are the same in that they are set at the same place and therefore indicate that a route is active.
In Varz, if you would want to know how many "routes" are defined, you really can only rely on `Varz.Cluster.URLs`, but it is not necessarily an indication of how many routes you want since one could use a DNS that resolves to multiple IPs.

For gateways, the `Varz.Gateway.Gateways` will report both configured and implicitly accepted gateways (that is, not configured). The `Gatewayz` page will have the information you want, with outbound and inbound, with information about if this is a configured gateway or not, and if connected, should have a `Connection` that is not nil.

**Comment by ripienaar** [comment]
OK, thanks for that, I'll have to remove these assertions as they are just completely wrong and revisit how best to figure out - long term this will anyway not be useful as we move to dynamic multi connection routes and gateways so I think best to just drop checking this now.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/329
