### ISSUE TITLE
Add stream source additional args

### ISSUE THREAD

**Issue by amelkikh** [nats-io/natscli#366]
Hi! 
I'm trying to create stream from source with `nats str add` and it would be useful to provide stream source information by cli args.
Something like:
- **--source-adjust** / **--no-source-adjust** or **--source-adjust** with bool type true/false
- **--source-seq-start** (int)
- **--source-start-at-utc** (string)
- **--source-subjects** (string)

Instead of always using interactive manual actions:
```
? Adjust source "EVENTS" start Yes
? EVENTS Source Start Sequence 0
? EVENTS Source UTC Time Stamp (YYYY:MM:DD HH:MM:SS) 
? EVENTS Source Filter source by subject [? for help] EVENTS
```

Thanks a lot!

**Comment by ripienaar** [comment]
there could be many sources, so how would you pick which one? It's too hard I thought since each of those arguments would also need to somehow pick a specific source to adjust. So for this reason we support this kind of thing:

```
nats s add SFO \
--source '{"name": "S1", "opt_start_seq": 10}' \
--source '{"name": "S2"}'
```

See the `sources` item in `nats schema show io.nats.jetstream.api.v1.stream_configuration`

**Comment by amelkikh** [comment]
> 
You helped me to solve all questions.
Thanks, colleague!
