### ISSUE TITLE
Report jetstream not enabled instead of no response from server

### ISSUE THREAD

**Issue by wallyqs** [nats-io/natscli#460]
When calling `nats account info` for example we currently throw a `no response from server` error in the case JetStream is not enabled. In nats.go we do this check to transform this error into a not enabled error for now: https://github.com/nats-io/nats.go/blob/7623eaad8b7d2fc29e5b21fb6577dba9690e0e1f/jsm.go#L198-L200

Something similar could be done for:

https://github.com/nats-io/jsm.go/blob/83c9d5c82c54be1b378fd83d1e9ea134942caa3d/manager.go#L79

https://github.com/nats-io/jsm.go/blob/83c9d5c82c54be1b378fd83d1e9ea134942caa3d/manager.go#L274-L280

**Comment by ripienaar** [comment]
It's a lot more involved than fixing it in the above locations - since in some cases you would get no responder when for example some resource does not exist even when JS is enabled.

So I'd rather handle that error in account info only

**Comment by ripienaar** [comment]
Also fwiw, account info api does not do no responders anymore - it used to.  Now it returns error 10039 because $JS.API.> always listen.

The mix of interactions between accounts, imports, exports, domains, selective permissions etc means you just cant know if jetstream is enabled and you also cant know if a no responders mean jetstream is disabled.

For this reason in some places like account info the server now has a not enabled error (10039) and responds with that.  It's just not safe to assume no responders mean jetstream is not enabled.

So I'll close this one.

**Comment by wallyqs** [comment]
sounds good to close, in the nats.go client we do `ErrJetStreamNotEnabled` when no responders and then `ErrNoStreamResponse` when it is the result of a js.publish etc...
