### ISSUE TITLE
NATS CLI pulls can leak subscriptions

### ISSUE THREAD

**Issue by tbeets** [nats-io/natscli#47]
Using NATS cli to pull consumer messages (nats consumer next <stream> <consumer>) orphaned Pull Request subscriptions on the consumer are created if there is no message to pull in that cli invocation.

**Comment by ripienaar** [comment]
Just a note the server will parse the expire list on every new message to avoid background timers etc.  So on an idle stream you will still see "orphans", but the important thing is they will not be sent any messages and will be expired.

The real problem is when:

```
subscribe(inbox)
while true
    poll(1)
    sleep(60)
```

and in a different thread you're consuming from the subscription, here you are creating 100s of polls AND the interest remains for the duration, in that scenario when 100 messages come in the inbox would get 100 messages not just the recent 1 that was asked.

In that scenario setting a timeout of 60 on the poll will mean when the messages do arrive you'll get just the 1 you expected from the most recent poll.  Regardless of whatever the server does internally with pending polls etc

**Comment by ripienaar** [comment]
done in https://github.com/nats-io/natscli/pull/48
