### ISSUE TITLE
Token authentication bug

### ISSUE THREAD

**Issue by boreddude13** [nats-io/natscli#476]
The logic used to choose token or username does not work properly, Connection reports: `Connection: nats: Authorization Violation`. When the CLI attempts to `nats.Connect()` it is calling this function under the hood to provide natsOpts: https://github.com/nats-io/jsm.go/blob/5a299917dacd0d9daafc9609afae4eed6107c816/natscontext/context.go#L294

The switch logic in this function will never set a token though for the created natsConnection since the CLI treats user/token the same. I was able to verify this is the case building the cli from source and removing the `c.User` (https://github.com/nats-io/jsm.go/blob/5a299917dacd0d9daafc9609afae4eed6107c816/natscontext/context.go#L298-L299). With this removed the token is properly set in the NATS connection and I can properly interface with my NATS server expecting a token.

**Comment by ripienaar** [comment]
Had a few bugs related to this, I think I will add a specific flag for tokens.

**Comment by ripienaar** [comment]
Looking again now I am not so sure this is the problem, we dont just always pass User from the CLI, it only sets the user if both a user and password is set, else it pass a token:

https://github.com/nats-io/natscli/blob/0f49ced81752e6eae21b3ee078ba4851114be158/cli/util.go#L749-L753

Given that, the context will do the right thing since it will only have the token option set.  

I guess what you cant do though is have a context with a user+password set and then override that with a token.  Is that what you were trying to do?

**Comment by ripienaar** [comment]
Closing this as working with the slight caveat, let me know if you have further issues
