### ISSUE TITLE
allow commands to be run without terminal

### ISSUE THREAD

**Issue by steevehook** [nats-io/natscli#533]
## Issue

As far as I understand the purpose of this utility is to make `nats` management easier by using this CLI utility instead. One particular thing I'm interested in and can't do it at the moment is run commands in detached mode. I keep getting the error below, as I'm trying to run this in a one time init Docker container

```text
nats: error: invalid input: cannot prompt for user input without a terminal
```

## Proposal

I know this is a bit of a bigger change, but I'd recommend to add some kind of Linux style `-y` flag or flags for filling in the survey. Otherwise one would only use this box to manually do things without any possible automation

**Comment by ripienaar** [comment]
It’s entirely useable without a terminal - there is a flag to supply every option they might result in a prompt. And the help in the prompts tells you what the flag that corresponds is.

**Comment by steevehook** [comment]
@ripienaar can you point me to that. I don't see it anywhere in the documentation or `cheat` command, neither in the actual `cli/command.go` file. It's simply using the `askOne` helper that errors if not in terminal input

**Comment by ripienaar** [comment]
nats s add —help. You have a option for every question 

see the CLI test - I run it through lots and lots of non interactive tests all by just supplying arguments

**Comment by steevehook** [comment]
Just found it recently 😄 Would be great to see which props are required, without inspecting the command source code. The terminal prompt error is just too generic

**Comment by ripienaar** [comment]
As a means of autonating the CLI though it’s not the answer alas since we keep adding things. Leading to more prompts. 

The only useful option is to use a config file

**Comment by steevehook** [comment]
I'm just saying as a completely new user I have 2 choices
- get doomed by the terminal prompt error
- try guessing which flags are required to satisfy the command validation

**Comment by ripienaar** [comment]
It’s not that simple. Some flags become required when others are given and others become incompatible in presence of others. 

It’s a hard problem - agree non interactive use is problematic, not sure there are fixes in the realm of “just simply ….” to the problem :(

**Comment by steevehook** [comment]
can I just get a full version of creating a stream non-interactively from the sensei?. I've been looking though those flags for at least 20 mins and can't make it work 😄

**Comment by ripienaar** [comment]
Are you saying that if it prompts you and you read the help for a prompt it doesn’t tell you what flag to pass? I mean the interactive prompts when it calls askOne. I think most if you press ? Will tell you the flag that would shut the prompt up. Hence that’s the easiest and friendliest way to discover since it also comes with a bit of description 

but for an example here are the tests 

https://github.com/nats-io/natscli/blob/dc9202ebb6b0887b182d1610b000c24d0aebe5d5/nats/nats_test.go#L209

**Comment by steevehook** [comment]
I try to run it as a docker-compose init container, to initialise my nats cluster. Since I run it in detached mode, I only get the generic error that I'm not in interactive mode

```yaml
nats-init:
    image: natsio/nats-box
    container_name: nats-init
    entrypoint: >
      sh -c 'nats context add nats --server n1:4222 --user=user --password=password --description "NATS Test" --select
      && nats stream add stream_name'
```

as I result these are the logs that I see

```
NATS Configuration Context "nats"

      Description: NATS Test
      Server URLs: n1:4222
         Username: user
         Password: *********
            Token: user
             Path: /nsc/.config/nats/context/nats.json
       Connection: OK

nats: error: invalid input: cannot prompt for user input without a terminal
```

**Comment by ripienaar** [comment]
Ok. But you didn’t start there as a brand new user. You ran it by hand (going with your analogy). So maybe start as a new user. Press the help options and supply flags to skip them? That’s a more realistic new user experience. 

As a docker init process it’s guaranteed to fail pretty much always as we always add new prompts. Your container init will regularly just stop working and be brittle. That’s how the tool is. It’s not made to solve that problem. 

Again, agreeing non interactive use is problematic and could improve but I am just trying to help you achieve your goal by saying how to discover the features of the tool today and that what you are trying will not go well for you within the realities of the system

**Comment by steevehook** [comment]
I guess in this case I'm better off running a simple Go script that creates the stream. I thought I could use a Docker image to have 1 less script to manage

**Comment by ripienaar** [comment]
I would, again, suggest to just give the CLI a config file :)

make a stream as you wish using whatever method - interactive or via a language or whatever - then do nats s info —json and pass that to nats s add in your docker init. 

This will remain relevant for much longer as rather than a tool to guide you through patterns and use cases and often used features it becomes a tool to just do what you ask it and the server side validation is relied on this will give you a much better outcome for your use case as the server sets defaults for lost things in line with your expectation.

**Comment by ripienaar** [comment]
I think it’s important to understand the CLI is designed almost as interactive docs, interactive discovery etc - most new features that are main line use cases are surfaced interactively and we often have users asking questions about what some feature is because we surface it in the CLI

so foremost it’s a discovery/learning/guidance tool hence the interaction. 

However advanced users can give it a config file and it will essentially turn off most of its annoyance and do basic validations only. 

Your use case is the last and you should use that feature. This is surfaced in tbe docs under configuration management for JetStream. 

And when that is not sufficient - it often isn’t - we have GitHub actions and terraform based tooling that shares an underlying library with the CLI ensuring which ever approach you take you get a consistent outcome.

**Comment by steevehook** [comment]
Again, same thing. No documentation on what that config file looks like. I could create a stream using a Go script, what's the point of this tool then

**Comment by steevehook** [comment]
Installing the Homebrew utility helped a bit, although, I'm a huge documentation fan. A little extra docs never killed nobody

**Comment by steevehook** [comment]
This is what an actual command looks like in order for it to succeed

```shell
nats stream add stream_name --user user --password password --subjects "s1,s2" --storage "file" --replicas 1 --retention limits --discard old --max-msgs 100 --max-msgs-per-subject 100 --max-bytes 2048 --max-age 5m --max-msg-size 1000 --dupe-window 2m --allow-rollup --no-deny-delete --no-deny-purge
```

I'm sure only 4-5 of them are really required, the rest can have defaults and improve the user experience. But my job is only to suggest. Took me 1h to get this right though a lot of guessing the flag name and its supported value
