### ISSUE TITLE
Add support for `--replicas=REPLICAS` to `nats consumer edit`

### ISSUE THREAD

**Issue by davidkemper** [nats-io/natscli#545]
The server now supports configuring the consumer replica count independent of the stream replication.

This also affects the `nats consumer edit` functionality through json/config. Adding the `num_replicas` field to the json had no effect, as it's unaware of the new setting.

**Comment by ripienaar** [comment]
Hmm, the --config option would have worked on nightly I think

**Comment by ripienaar** [comment]
The reason this is not surfaced in the CLI via edit etc is because it just does not work well.  These features are too new and emergant and under active bug fixing.  So once its ready I'll activate the --replicas flag in edit.

For example, R3->R1->R3 you get a timeout and no server response on the last resize and the resize just doesnt work, this is not fit for wide use yet

**Comment by davidkemper** [comment]
Understood. Workaround available (send direct system messages) until it's ready.

**Comment by ripienaar** [comment]
Still not right, filed https://github.com/nats-io/nats-server/issues/3493

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/645
