### ISSUE TITLE
color-code by value in a column

### ISSUE THREAD

**Issue by philpennock** [nats-io/natscli#629]
I think it would be useful to be able to run something like:

```sh
nats server list --sort=name --color-line-by=version
```

and have the reporting use a different color for each line, based upon the value in the Version column.

I don't remember the details but I believe that there are collections of color-codes chosen such that each is visually distinct, and legible against both light and dark backgrounds; so by just assigning sequentially from that set of codes for each version seen, we'd get output color-coded by the server version.  It doesn't need to be sorted by the version: just the first value seen gets colour A, the second value gets colour B, and so distinct invocations might change the colors used.  That's fine to me, but others might disagree.

**Comment by ripienaar** [comment]
Will close this as in another request we made it now warn of missmatches.  Does help with knowing something is bad - if not yet with highlighting the exact spot.

Picking CLI colors is a nightmare since so many people have so many different terminal setups.  One day maybe the cli will have a config file making these setable by users, for now, whatever colors I pick will annoy some people so it just doesnt seem viable for forseeable future.
