### ISSUE TITLE
Allow consumer INFO json to be directly used as --config to create an identical consumer

### ISSUE THREAD

**Issue by tbeets** [nats-io/natscli#713]
For convenience and compatibility with full INFO json response, adding a consumer by config should work identically for these two documents:

The value of the config element from INFO:
```json
{
  "ack_policy": "explicit",
  "ack_wait": 30000000000,
  "deliver_policy": "all",
  "durable_name": "bobo",
  "filter_subject": "stl.tx",
  "max_ack_pending": 1000,
  "max_deliver": -1,
  "max_waiting": 512,
  "replay_policy": "instant",
  "num_replicas": 0
}
```
INFO full document:
```json
{
  "stream_name": "TX-FEED",
  "name": "bobo",
  "config": {
    "durable_name": "bobo",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": -1,
    "filter_subject": "stl.tx",
    "replay_policy": "instant",
    "max_waiting": 512,
    "max_ack_pending": 1000,
    "num_replicas": 0
  }
...
}
```

According to @ripienaar , stream add already implements this convenience, but as of 0.35.0 of CLI, using the full document (as above) will go silently, but will create a consumer named "bobo" with all defaults (including default expiry).

/cc: @bruth

**Comment by ripienaar** [comment]
Done in https://github.com/nats-io/natscli/pull/714

It's quite scary though, I was overruled in requests to type or version these various structs, so we are now in a situation where `{}` is a valid configuration for consumers.

You can literally send in a stream info output into consumer create, it will create a thing and its impossible to really detect and there's now no sane kind of validation that can be done in schemas since even empty object is valid.

Had these data structs been typed we could have detected errors, for now its definitely a chance or just random weird things happening when passing in json files like this.

**Comment by diorcety** [comment]
@ripienaar The stream_name from the json file is not used. When using 
`nats consumer add --config test.json`
The question "Select a Stream" is asked

**Comment by ripienaar** [comment]
Yes it only uses the config. You need to supply the stream
