### ISSUE TITLE
Can't dump `stream view` messages to file or pipe if stream has >10 messages

### ISSUE THREAD

**Issue by mprimi** [nats-io/natscli#820]
Trying to dump the content of a stream to file (or pipe into a different command like `grep`, `wc`, etc), result into a stuck `nats` process that can't be easily terminated.

## Repro steps:
1. Create a stream with > 10 messages
2. Dump stream content to a file:
  * `nats  stream view my-stream > ~/stream.txt`

### Result:
Process emits the first 10 messages then hangs forever. 
Cannot be easily killed via ctrl-c.

### Misc

`nats` does not seem to realize is being piped (i.e. non-interactive mode), so after emitting the first 10 messages it will wait for the user to say `yes` to move to the next page. However stdin is not linked, so one cannot even "blindly" say yes. 
The process is stuck (forever) waiting for input which can't come.

To avoid pagination, I tried to set page size to a very large number (e.g., `nats  stream view my-stream 1000000 | ...`).
This should work in principle, but doesn't work in practice because of an [hardcoded limit of 25 messages per page](https://github.com/nats-io/natscli/blob/main/cli/stream_command.go#L666) which can't be overridden.

**Comment by ripienaar** [comment]
That’s just not what stream view is for :)  It’s for interactive viewing. If anything it should fail on no TTY. 

nats sub is probsbly better for this kind of thing and it supports dumping messages to files etc.

**Comment by mprimi** [comment]
Thank you for the clarification.

I thought `view` is the closest to what i want, because `sub`:
 - Emits JSON with encoded payload, harder for humans inspection
 - No separators between messages, hard to stream-process with pipes
 - I'd prefer not to create a subscriber because that changes the system state
 - Can't target a stream, only target a subject
 - Also hangs forever waiting for new messages
 
Wouldn't it be nice if `view` could be used to dump to file or pipe, in addition to the current interactive mode?

**Comment by ripienaar** [comment]
Sub on a stream also changes the system stage - just like view both makes a consumer. 

nats sub is what you want. Can dump to files. Support decoders etc (on main)

**Comment by ripienaar** [comment]
Also doesnt hang forever, it has timeouts after a period of no traffic that you can enable. Can target a stream using --bind

Please look at main and --help

View is for viewing, sub is your swiss army knife for receving and processing messages

**Comment by philpennock** [comment]
I just encountered this same issue.  It might not be what `view` is for, but even so nats should not hang and fail to exit when sent SIGTERM.  Where the prompt would have happened, instead it just locks up.   I wanted to dump the history of an existing stream and grep for certain messages, and was very confused when `nats str view XYZ | grep ABC` hung for a long time, and then couldn't be killed without `-9`.

**Comment by ripienaar** [comment]
Agree and as I mentioned above, it should fail with an error without a TTY.

**Comment by mprimi** [comment]
For future reference, the closest thing to `nats  stream view my-stream > ~/stream.txt` (suggested by @ripienaar):
`nats sub --stream my-stream --all --wait=1s --dump -- - | xargs -0 echo | jq -r '.Data|@base64d' > stream.txt`

This dumps decoded messages, so could be useful. In my case tho, I'd still prefer `stream view` because it shows the sequence numbers, which are not available in `sub` from what i can tell.

@ripienaar: if i submit a patch for `stream view` do disable pagination in case of no TTY, would you take it? 
(conditional on  you liking the implementation of course)

**Comment by ripienaar** [comment]
No I think stream view is for viewing. We can improve sub to make your use case better or easier.

**Comment by mprimi** [comment]
So you have a program, it works great, it output texts. But if i want to output the same to a file, it blocks me. 

Out of curiosity.. Do you have chip on your shoulder against the unix philosophy?

**Comment by ripienaar** [comment]
> So you have a program, it works great, it output texts. But if i want to output the same to a file, it blocks me.
> 
> Out of curiosity.. Do you have chip on your shoulder against the unix philosophy?

I don't think this kind of message is called for, I am trying to help you, lets keep it civil and mature.

I do not have a propblem with the unix philosophy as you can tell from `sub`, I do have a problem with every command having millions of options, complexity, behaviours and user overhead.  There is value in having a command do 1 thing and doing it well.  We have 1 interactive viewer and one generic tool for interacting with messages and passing it to various other locations in many different ways, why do we need 2 that are slightly different?

`nats sub` is quite a complex with many options and behaviours, but it also started super simple and we also just wanted to add one little behaviour to facilitate one other use case.  Just like you're trying to do with s view and over time this kept happening - because its never that simple - and so we end up with a big complex tool.

Now sub does what you want, maybe we can make some improvements here and there to make it work better since due to its many behaviours and many congtributors we might have some weird combinations of options that doesnt work well.  So lets improve that, and make a really good all round tool for the problem you are having - and not just that one problem but the entire class of problem.

What I dont want to do is recreate the complexity, maintenance hassles, user cognitive overheard etc also in view when view does just one thing and does it well.

So, I ask you, whats the difference between:

```
$ nats s view SUB
[8] Subject: js.in.sub Received: 2023-07-11T04:46:14Z

bWVzc2FnZSA4Cg==

[9] Subject: js.in.sub Received: 2023-07-11T04:46:14Z

bWVzc2FnZSA5Cg==
```

and

```
$ nats sub --stream SUB 
[#93] Received JetStream message: stream: SUB seq 93 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
bWVzc2FnZSA5Mwo=

[#94] Received JetStream message: stream: SUB seq 94 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
bWVzc2FnZSA5NAo=

[#95] Received JetStream message: stream: SUB seq 95 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
bWVzc2FnZSA5NQo=

[#96] Received JetStream message: stream: SUB seq 96 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
bWVzc2FnZSA5Ngo=
```

Why is trying to process output of view better than sub for you? Sub supports piping etc exactly as you wish?

Now les see how we translate the base64 encoded payloads:

```
$ nats sub --stream SUB --translate "base64 -d"
[#95] Received JetStream message: stream: SUB seq 95 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
message 95

[#96] Received JetStream message: stream: SUB seq 96 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
message 96

[#97] Received JetStream message: stream: SUB seq 97 / subject: js.in.sub / time: 2023-07-11T04:46:16Z
message 97
```

And again you can pipe this wherever you like, whats wrong with this output?

If you just want to see the bodies and not any of the other text, also easy:

```
$ nats sub --stream SUB --raw
bWVzc2FnZSA4Mgo=
bWVzc2FnZSA4Mwo=
bWVzc2FnZSA4NAo=
bWVzc2FnZSA4NQo=
bWVzc2FnZSA4Ngo=
bWVzc2FnZSA4Nwo=
bWVzc2FnZSA4OAo=
bWVzc2FnZSA4OQo=
```

Though this doesnt appear to support `--translate` it probably should, this is also easy to pipe wherever you like.

If you want to process the entire message - headers and all and only base64 decode one key in the json. Well you can do that like I described earlier by piping using null terminated strings the messages into other tools that are built for that behavious like xargs.

```
$ nats sub --stream SUB_HDRS --wait 1s --dump -- -|xargs -0 -n1 -I {} echo {}|jq '{"headers":.Header|length, "body":.Data|@base64d|length}'
{
  "headers": 1,
  "body": 16
}
{
  "headers": 1,
  "body": 16
}
{
  "headers": 1,
  "body": 16
}
```

**Comment by ripienaar** [comment]
Also worth noting that the plan for `s view` is to be a more interactive browser, something like list of streams on the left and messages on that right, you can jump between panes, or select a message for details and jump around the stream etc.

I am not aware that the unix philosophy *requires* every application to be pipeable, interactive applications are allowed and its quite common that they have no pipable behavious.

**Comment by mprimi** [comment]
@ripienaar i swear i wasn't trying to insult you or disrespect you, that was a failed attempt at humor.
Of course you don't have a chip on your shoulder with the UNIX philosophy, I thought it would be absurd (funny) to frame the  question that way. 

The underlying question was just 'why'.  The command was outputting in good format, I just want to pipe it, and now it's going to block me altogether. Why?

Your answer makes sense (`view` is a placeholder for a TUI stream explorer). And so does every other answer you provided in this thread. I didn't dispute any of it, you're the maintainer, the tool is great, and i have no reason to doubt your choices. 

---

Regarding using `sub` instead of view. Looks like `nats sub --stream SUB --translate "base64 -d"` does exactly what I need. The `sub` command you had suggested in slack used `--dump` which doesn't play well with `--translate`, so i was left thinking that there was no way to output something `view`-like. Updating my comment above for any future reader.

**Comment by ccope** [comment]
So I'm new to nats and trying to debug some downstream parsing logic. I want to just dump the messages from the past few hours to look for something, without making the system consider those events as "processed". I went from interactively paging through the first few dozen messages to trying to pipe it to a file and hitting this error. This command already takes a "since" argument and a page size argument. It seems a bit counter-productive to block piping the output, that sent me down a rabbit hole trying to figure out how to disable pagination. Constructing options for an equivalent `nats sub` command seems more tricky.

**Comment by Kinrany** [comment]
A critical part of using a shell command is using it manually, learning its behavior, and then incorporating it in a script to automate its use. A command that can only be used automatically is immediately inferior to another command that can do the same, with slightly worse UX, but both interactively and non-interactively alike.

**Comment by ripienaar** [comment]
We are converging a lot of things into sub - like consumer sub and more.  It view is quite different that it would be a bit weird to wedge in there. 

It’s a balance between adding many flags and making it too hard to figure out what it does vs having 2 commands. 

Sub does A LOT already.
